# Generated by Django 2.2.3 on 2019-08-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Awaiting Boarding', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(db_index=True, default='tk-a9tfrtepx', editable=False, max_length=100, unique=True),
        ),
    ]
