# Generated by Django 2.2.3 on 2019-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plane_category', models.CharField(max_length=255)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('expected_arrival_time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('ticket_price', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
