# Generated by Django 2.2.3 on 2019-08-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='booked_seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(db_index=True, default='fn-7qgty2n78', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='expected_arrival_time',
            field=models.TimeField(),
        ),
    ]
